# Generated by Django 4.1.5 on 2023-09-08 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('nest_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)])),
                ('wingspan', models.PositiveIntegerField(default=1)),
                ('feathers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('ability_desc', models.CharField(max_length=200)),
                ('cached_food', models.PositiveIntegerField(default=0)),
                ('tucked_cards', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
