# Generated by Django 4.1.5 on 2023-09-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forest1', to='aviary.birdcard')),
                ('forest_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forest2', to='aviary.birdcard')),
                ('forest_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forest3', to='aviary.birdcard')),
                ('forest_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forest4', to='aviary.birdcard')),
                ('forest_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forest5', to='aviary.birdcard')),
                ('grassland_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grassland1', to='aviary.birdcard')),
                ('grassland_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grassland2', to='aviary.birdcard')),
                ('grassland_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grassland3', to='aviary.birdcard')),
                ('grassland_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grassland4', to='aviary.birdcard')),
                ('grassland_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Grassland5', to='aviary.birdcard')),
                ('wetland_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Wetland1', to='aviary.birdcard')),
                ('wetland_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Wetland2', to='aviary.birdcard')),
                ('wetland_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Wetland3', to='aviary.birdcard')),
                ('wetland_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Wetland4', to='aviary.birdcard')),
                ('wetland_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Wetland5', to='aviary.birdcard')),
            ],
        ),
    ]
