# Generated by Django 4.1.5 on 2023-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcard',
            name='ability_type',
            field=models.CharField(choices=[('w', 'White'), ('b', 'Brown'), ('t', 'Teal'), ('y', 'Yellow'), ('p', 'Pink')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='nest_type',
            field=models.CharField(choices=[('g', 'Ground'), ('c', 'Cavity'), ('b', 'Bowl'), ('s', 'Stick'), ('n', 'None'), ('a', 'Star')], default='n', max_length=1),
        ),
    ]
