# Generated by Django 4.1.5 on 2023-09-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0003_birdcard_ability_type_birdcard_nest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(default='default', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='forest_nectar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='grassland_nectar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='wetland_nectar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FoodJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.birdcard')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviary.foods')),
            ],
        ),
    ]
