# Generated by Django 4.1.5 on 2023-09-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0005_birdcard_direction_facing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitat_name', models.CharField(default='forest', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='birdcard',
            name='habitats',
            field=models.ManyToManyField(to='aviary.habitats'),
        ),
    ]
