# Generated by Django 4.1.5 on 2023-09-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0007_alter_birdcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcard',
            name='image',
        ),
    ]
