# Generated by Django 4.1.5 on 2023-09-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0008_remove_birdcard_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habitats',
            new_name='Habitat',
        ),
    ]
