# Generated by Django 4.1.5 on 2023-09-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0011_remove_foodjunction_food_id_foodjunction_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodjunction',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='foodjunction',
            old_name='food_id',
            new_name='food',
        ),
    ]
