# Generated by Django 4.1.5 on 2023-12-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0015_endroundgoals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndRoundGoals',
            new_name='EndRoundGoal',
        ),
    ]
