# Generated by Django 5.2 on 2025-04-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0016_rename_endroundgoals_endroundgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdcard',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='foodjunction',
            options={'ordering': ['card__name']},
        ),
    ]
