# Generated by Django 5.2 on 2025-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0017_alter_birdcard_options_alter_foodjunction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_of_round_1_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal1', to='aviary.endroundgoal'),
        ),
        migrations.AddField(
            model_name='board',
            name='end_of_round_2_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal2', to='aviary.endroundgoal'),
        ),
        migrations.AddField(
            model_name='board',
            name='end_of_round_3_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal3', to='aviary.endroundgoal'),
        ),
        migrations.AddField(
            model_name='board',
            name='end_of_round_4_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal4', to='aviary.endroundgoal'),
        ),
    ]
