# Generated by Django 5.2.1 on 2025-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0018_board_end_of_round_1_goal_board_end_of_round_2_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus', models.CharField(choices=[('No Bonus', 'No Bonus'), ('Forester', 'Birds that can only live in the forest'), ('Prairie Manager', 'Birds that can only live in the grassland'), ('Wetland Scientist', 'Birds that can only live in the wetland'), ('Bird Feeder', 'Birds that eat wheat'), ('Food Web Expert', 'Birds that can only eat worms'), ('Fishery Manager', 'Birds that eat fish'), ('Omnivore Expert', 'Birds that eat wild'), ('Rodentologist', 'Birds that eat rats'), ('Viticulturalist', 'Birds that eat cherries'), ('Anatomist', 'Birds with body parts in their names'), ('Cartographer', 'Birds with geographic terms in their names'), ('Historian', 'Birds named after a person'), ('Photographer', 'Birds with a color in their name'), ('Breeding Manager', 'Birds that have at least 4 eggs'), ('Oologist', 'Birds that have at least 1 egg'), ('Enclosure Builder', 'Birds with ground nests'), ('Nest Box Builder', 'Birds with cavity nests'), ('Platform Builder', 'Birds with stick nests'), ('Wildlife Gardener', 'Birds with bowl nests'), ('Backyard Birder', 'Birds worth less than 4 points'), ('Passerine Specialist', 'Birds with wingspan 30cm or less'), ('Large Bird Specialist', 'Birds with wingspan more than 65cm'), ('Bird Counter', 'Birds with a tucking power'), ('Falconer', 'Birds with a death power'), ('Ecologist', 'Birds in your habitat with the fewest birds'), ('Visionary Leader', 'Bird cards in hand at the end of the game')], default='No Bonus', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='end_of_round_1_goal',
        ),
        migrations.RemoveField(
            model_name='board',
            name='end_of_round_2_goal',
        ),
        migrations.RemoveField(
            model_name='board',
            name='end_of_round_3_goal',
        ),
        migrations.RemoveField(
            model_name='board',
            name='end_of_round_4_goal',
        ),
        migrations.RemoveField(
            model_name='endroundgoal',
            name='board',
        ),
        migrations.RemoveField(
            model_name='endroundgoal',
            name='round',
        ),
        migrations.AlterField(
            model_name='endroundgoal',
            name='goal',
            field=models.CharField(choices=[('No Goal', 'No Goal'), ('Eggs in Forest', 'Eggs in Forest'), ('Eggs in Grassland', 'Eggs in Grassland'), ('Eggs in Wetland', 'Eggs in Wetland'), ('Birds in Forest', 'Birds in Forest'), ('Birds in Grassland', 'Birds in Grassland'), ('Birds in Wetland', 'Birds in Wetland'), ('Bird Food Cost', 'Food Cost of Played Birds'), ('Worms in Food Cost', 'Worms in Food Cost'), ('Cherries and Wheat in Food Cost', 'Cherries and Wheat in Food Cost'), ('Fish and Rats in Food Cost', 'Fish and Rats in Food Cost'), ('Birds with Tucked Cards', 'Birds with Tucked Cards'), ('Brown Birds', 'Brown Birds'), ('White Birds', 'White or No Power Birds'), ('Eggs in Cavity', 'Eggs in Cavity'), ('Eggs in Bowl', 'Eggs in Bowl'), ('Eggs in Stick', 'Eggs in Stick'), ('Eggs in Ground', 'Eggs in Ground'), ('Cavity Birds with Eggs', 'Cavity Birds with Eggs'), ('Bowl Birds with Eggs', 'Bowl Birds with Eggs'), ('Stick Birds with Eggs', 'Stick Birds with Eggs'), ('Ground Birds with Eggs', 'Ground Birds with Eggs'), ('Birds with No Eggs', 'Birds with No Eggs'), ('Birds worth <4', 'Birds worth <4 points'), ('Birds worth >4', 'Birds worth >4 points'), ('Food in Personal Supply', 'Food in Personal Supply'), ('Bird Cards in Hand', 'Bird Cards in Hand'), ('Sets of Eggs', 'Sets of Eggs'), ('Filled Columns', 'Filled Columns'), ('Birds in a Row', 'Birds in a Row'), ('Number of Played Birds', 'Number of Played Birds'), ('Beaks Pointing Right', 'Beaks Pointing Right'), ('Beaks Pointing Left', 'Beaks Pointing Left'), ('Cubes on "Play a Bird"', 'Cubes on "Play a Bird"')], default='No Goal', max_length=50),
        ),
        migrations.AlterField(
            model_name='endroundgoal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
