# Generated by Django 5.2 on 2025-04-29 01:40

import aviary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0019_remove_endroundgoal_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='end_of_round_1_goal',
            field=models.ForeignKey(default=aviary.models.EndRoundGoal.create_default_goal, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='EndRoundGoal1', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_2_goal',
            field=models.ForeignKey(default=aviary.models.EndRoundGoal.create_default_goal, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='EndRoundGoal2', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_3_goal',
            field=models.ForeignKey(default=aviary.models.EndRoundGoal.create_default_goal, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='EndRoundGoal3', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_4_goal',
            field=models.ForeignKey(default=aviary.models.EndRoundGoal.create_default_goal, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='EndRoundGoal4', to='aviary.endroundgoal'),
        ),
    ]
