# Generated by Django 5.2.1 on 2025-05-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0020_board_end_of_round_1_goal_board_end_of_round_2_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endroundgoal',
            name='goal',
            field=models.CharField(choices=[('No Goal', 'No Goal'), ('Eggs in Forest', 'Eggs in Forest'), ('Eggs in Grassland', 'Eggs in Grassland'), ('Eggs in Wetland', 'Eggs in Wetland'), ('Birds in Forest', 'Birds in Forest'), ('Birds in Grassland', 'Birds in Grassland'), ('Birds in Wetland', 'Birds in Wetland'), ('Bird Food Cost', 'Food Cost of Played Birds'), ('Worms in Food Cost', 'Worms in Food Cost'), ('Cherries and Wheat in Food Cost', 'Cherries and Wheat in Food Cost'), ('Fish and Rats in Food Cost', 'Fish and Rats in Food Cost'), ('Birds with Tucked Cards', 'Birds with Tucked Cards'), ('Brown Birds', 'Birds with Brown Power'), ('White Birds', 'Birds with White or No Power'), ('Eggs in Cavity', 'Eggs in Cavity Nests'), ('Eggs in Bowl', 'Eggs in Bowl Nests'), ('Eggs in Stick', 'Eggs in Stick Nests'), ('Eggs in Ground', 'Eggs in Ground Nests'), ('Cavity Birds with Eggs', 'Cavity Nest Birds with Eggs'), ('Bowl Birds with Eggs', 'Bowl Nest Birds with Eggs'), ('Stick Birds with Eggs', 'Stick Nest Birds with Eggs'), ('Ground Birds with Eggs', 'Ground Nest Birds with Eggs'), ('Birds with No Eggs', 'Birds with No Eggs'), ('Birds worth <4', 'Birds worth <4 points'), ('Birds worth >4', 'Birds worth >4 points'), ('Food in Personal Supply', 'Food in Personal Supply'), ('Bird Cards in Hand', 'Bird Cards in Hand'), ('Sets of Eggs', 'Sets of Eggs'), ('Filled Columns', 'Filled Columns'), ('Birds in a Row', 'Birds in one Row'), ('Number of Played Birds', 'Number of Played Birds'), ('Beaks Pointing Right', 'Beaks Pointing Right'), ('Beaks Pointing Left', 'Beaks Pointing Left'), ('Cubes on "Play a Bird"', 'Cubes on "Play a Bird"')], default='No Goal', max_length=50),
        ),
    ]
