# Generated by Django 5.2.1 on 2025-06-10 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0025_board_draw_cards_cubes_board_gain_food_cubes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdcard',
            name='food_cost',
            field=models.ManyToManyField(to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='is_food_cost_one',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BirdCardScaffold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bird', max_length=50)),
                ('nest_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)])),
                ('nest_type', models.CharField(choices=[('g', 'Ground'), ('c', 'Cavity'), ('b', 'Bowl'), ('s', 'Stick'), ('n', 'None'), ('a', 'Star')], default='n', max_length=1)),
                ('wingspan', models.PositiveIntegerField(default=1)),
                ('feathers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('ability_desc', models.CharField(default='No ability', max_length=200)),
                ('ability_type', models.CharField(choices=[('w', 'White'), ('b', 'Brown'), ('t', 'Teal'), ('y', 'Yellow'), ('p', 'Pink')], default='w', max_length=1)),
                ('direction_facing', models.CharField(choices=[('r', 'Right'), ('l', 'Left'), ('f', 'Forward')], default='f', max_length=1)),
                ('is_food_cost_one', models.BooleanField(default=True)),
                ('food_cost', models.ManyToManyField(to='aviary.food')),
                ('habitats', models.ManyToManyField(to='aviary.habitat')),
            ],
        ),
    ]
