# Generated by Django 5.2.1 on 2025-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0026_birdcard_food_cost_birdcard_is_food_cost_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcard',
            name='food_cost',
        ),
        migrations.RemoveField(
            model_name='birdcard',
            name='is_food_cost_one',
        ),
    ]
