# Generated by Django 5.2.1 on 2025-06-11 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0027_remove_birdcard_food_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcardscaffold',
            name='food_cost',
        ),
        migrations.RemoveField(
            model_name='birdcardscaffold',
            name='is_food_cost_one',
        ),
        migrations.AddField(
            model_name='birdcardscaffold',
            name='costs_one_food',
            field=models.BooleanField(default=False, help_text='Does this bird cost one food to play?'),
        ),
        migrations.AddField(
            model_name='birdcardscaffold',
            name='first_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='first_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardscaffold',
            name='second_food',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardscaffold',
            name='third_food',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_food', to='aviary.food'),
        ),
    ]
