# Generated by Django 5.2.1 on 2025-06-13 02:19

import aviary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0028_remove_birdcardscaffold_food_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bird', max_length=50)),
                ('nest_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)])),
                ('nest_type', models.CharField(choices=[('g', 'Ground'), ('c', 'Cavity'), ('b', 'Bowl'), ('s', 'Stick'), ('n', 'None'), ('a', 'Star')], default='n', max_length=1)),
                ('wingspan', models.PositiveIntegerField(default=1)),
                ('feathers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('ability_desc', models.CharField(default='No ability', max_length=200)),
                ('ability_type', models.CharField(choices=[('w', 'White'), ('b', 'Brown'), ('t', 'Teal'), ('y', 'Yellow'), ('p', 'Pink')], default='w', max_length=1)),
                ('direction_facing', models.CharField(choices=[('r', 'Right'), ('l', 'Left'), ('f', 'Forward')], default='f', max_length=1)),
                ('costs_one_food', models.BooleanField(default=False, help_text='Does this bird cost one food to play?')),
                ('first_food', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='first_food', to='aviary.food')),
                ('habitats', models.ManyToManyField(to='aviary.habitat')),
                ('second_food', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_food', to='aviary.food')),
                ('third_food', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_food', to='aviary.food')),
            ],
        ),
        migrations.DeleteModel(
            name='BirdCardScaffold',
        ),
    ]
