# Generated by Django 5.2.1 on 2025-06-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0029_birdcardtemplate_delete_birdcardscaffold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='draw_cards_cubes',
            new_name='draw_bird_cards_cubes',
        ),
        migrations.AddField(
            model_name='birdcard',
            name='costs_one_food',
            field=models.BooleanField(default=False, help_text='Does this bird cost one food to play?'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='first_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_first_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='second_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_second_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='third_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_third_food', to='aviary.food'),
        ),
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='first_food',
        ),
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='second_food',
        ),
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='third_food',
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='first_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_template_first_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='second_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_template_second_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='third_food',
            field=models.ManyToManyField(blank=True, default=None, related_name='birdcard_template_third_food', to='aviary.food'),
        ),
    ]
