# Generated by Django 5.2.1 on 2025-07-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0030_rename_draw_cards_cubes_board_draw_bird_cards_cubes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcard',
            name='first_food',
        ),
        migrations.RemoveField(
            model_name='birdcard',
            name='second_food',
        ),
        migrations.RemoveField(
            model_name='birdcard',
            name='third_food',
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_1_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal1', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_2_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal2', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_3_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal3', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_of_round_4_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EndRoundGoal4', to='aviary.endroundgoal'),
        ),
        migrations.AlterField(
            model_name='endroundgoal',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='first_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_first_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='second_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_second_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcard',
            name='third_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_third_food', to='aviary.food'),
        ),
    ]
