# Generated by Django 5.2.1 on 2025-07-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0031_remove_birdcard_first_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='first_food',
        ),
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='second_food',
        ),
        migrations.RemoveField(
            model_name='birdcardtemplate',
            name='third_food',
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='first_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_template_first_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='second_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_template_second_food', to='aviary.food'),
        ),
        migrations.AddField(
            model_name='birdcardtemplate',
            name='third_food',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdcard_template_third_food', to='aviary.food'),
        ),
    ]
